/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Inter;

import Cod.Logs;
import Cod.ManejoUsuario;
import Cod.Usuario;

/**
 *
 * @author Dell
 */
public class Historial extends javax.swing.JPanel {

    private ManejoUsuario user;
    
    public Historial(ManejoUsuario user) {
        this.user=user;
        initComponents();
        area.setEditable(false);
        
         area.setLineWrap(true); 
        area.setWrapStyleWord(true);
        mostrarLogs();
        
        
        
        
        
    }
    
    public void mostrarLogs(){
        area.setText("");
        
        Usuario usuarioActual = user.obtenerUsuarioActual();
        Logs[] logsAct = usuarioActual.getLogs();
        
        StringBuilder Acumulados = new StringBuilder();
        for (int i = logsAct.length - 1; i >= 0; i--) {
            if (logsAct[i] != null) {
                    Acumulados.append(logsAct[i].toString()).append("\n"); 
            }
        }
        area.setText(Acumulados.toString());

        revalidate();
        repaint();

        
       
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();

        setPreferredSize(new java.awt.Dimension(720, 390));

        area.setColumns(20);
        area.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        area.setForeground(new java.awt.Color(0, 0, 0));
        area.setRows(5);
        jScrollPane1.setViewportView(area);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
