/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Inter;

import Cod.ManejoUsuario;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class Iniciar_Sesion extends javax.swing.JFrame {
   
   private ManejoUsuario user; 
   
    
    /**
     * Creates new form Iniciar_Sesion
     */
    public Iniciar_Sesion(ManejoUsuario user) {
        this.user=user;
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main1 = new Cod.Main();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txusername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        bnX = new javax.swing.JButton();
        bnIniciar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        chmostrar = new javax.swing.JCheckBox();
        jpasswor = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jpassword = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Siguiente");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 580, 130, 30));

        jLabel10.setFont(new java.awt.Font("Japanese", 1, 26)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("hoLA JA JA YQ AK A OE PXN A");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, 540, 40));

        jLabel1.setFont(new java.awt.Font("Japanese", 1, 62)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(" A E I");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 230, 310, 110));

        txusername.setBackground(new java.awt.Color(102, 0, 0));
        txusername.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        txusername.setForeground(new java.awt.Color(255, 255, 255));
        txusername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 2));
        txusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txusernameActionPerformed(evt);
            }
        });
        txusername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txusernameKeyTyped(evt);
            }
        });
        getContentPane().add(txusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, 261, 40));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Back");
        jLabel3.setToolTipText("");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 50, 20));

        bnX.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        bnX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imags/button_back.png"))); // NOI18N
        bnX.setBorderPainted(false);
        bnX.setContentAreaFilled(false);
        bnX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnXActionPerformed(evt);
            }
        });
        getContentPane().add(bnX, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 60));

        bnIniciar.setBackground(new java.awt.Color(255, 255, 255));
        bnIniciar.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        bnIniciar.setForeground(new java.awt.Color(0, 0, 0));
        bnIniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imags/button2.png"))); // NOI18N
        bnIniciar.setBorderPainted(false);
        bnIniciar.setContentAreaFilled(false);
        bnIniciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnIniciarActionPerformed(evt);
            }
        });
        getContentPane().add(bnIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 560, 290, 70));

        jLabel4.setFont(new java.awt.Font("KATANA", 0, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Contraseña");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, 260, 30));

        chmostrar.setBackground(new java.awt.Color(102, 0, 0));
        chmostrar.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        chmostrar.setForeground(new java.awt.Color(255, 255, 255));
        chmostrar.setText("Mostrar contraseña");
        chmostrar.setOpaque(true);
        chmostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chmostrarActionPerformed(evt);
            }
        });
        getContentPane().add(chmostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 510, -1, -1));

        jpasswor.setBackground(new java.awt.Color(102, 0, 0));
        jpasswor.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jpasswor.setForeground(new java.awt.Color(255, 255, 255));
        jpasswor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 2));
        getContentPane().add(jpasswor, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 460, 260, 40));

        jLabel7.setFont(new java.awt.Font("KATANA", 0, 38)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Inicia sesion ");
        jLabel7.setToolTipText("");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 300, 100));

        jLabel6.setFont(new java.awt.Font("KATANA", 1, 40)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 102, 102));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imags/botonG.png"))); // NOI18N
        jLabel6.setToolTipText("");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 430, 150));

        jLabel5.setFont(new java.awt.Font("KATANA", 0, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Nombre de usuario");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, 260, 30));

        jpassword.setBackground(new java.awt.Color(0, 0, 0));
        jpassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imags/55.png"))); // NOI18N
        jpassword.setOpaque(true);
        getContentPane().add(jpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txusernameActionPerformed

    private void txusernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txusernameKeyTyped

    }//GEN-LAST:event_txusernameKeyTyped

    private void bnXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnXActionPerformed
        this.setVisible(false);
        new Menu_Inicio(user).setVisible(true);
    }//GEN-LAST:event_bnXActionPerformed

    private void bnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnIniciarActionPerformed
        String username = txusername.getText();
        String password = new String(jpasswor.getPassword());

        if (!username.isEmpty() && !password.isEmpty()) {

            if (user.validarCredenciales(username, password)) {

                if(user.obtenerUsuarioActual().getEstado()==false){
                    user.cambiarEstadoUsuario(user.obtenerUsuarioActual().getUsername(), true);
                    JOptionPane.showMessageDialog(null, "Tu cuenta ha sido activada nuevamente");

                }else{
                    user.cambiarEstadoUsuario(user.obtenerUsuarioActual().getUsername(), true);
                    JOptionPane.showMessageDialog(null, "Bienvenido :)");}
                //Perfil perfil = new Perfil(user);

                this.setVisible(false);
                new Menu_Principal(user).setVisible(true);

            } else if(user.usuarioExiste(username)){
                JOptionPane.showMessageDialog(null, "Verifique la informacion");

            } else {
                JOptionPane.showMessageDialog(null, "El usuario no existe");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Error! Campos Vacios");
        }

    }//GEN-LAST:event_bnIniciarActionPerformed

    private void chmostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chmostrarActionPerformed
        if (chmostrar.isSelected()) {
            jpasswor.setEchoChar((char)0);
        } else {

            jpasswor.setEchoChar('*');
        }
    }//GEN-LAST:event_chmostrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Iniciar_Sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Iniciar_Sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Iniciar_Sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Iniciar_Sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            ManejoUsuario user;
            public void run() {
                new Iniciar_Sesion(user).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnIniciar;
    private javax.swing.JButton bnX;
    private javax.swing.JCheckBox chmostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField jpasswor;
    private javax.swing.JLabel jpassword;
    private Cod.Main main1;
    private javax.swing.JTextField txusername;
    // End of variables declaration//GEN-END:variables
}
