/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Inter;


import Cod.ManejoUsuario;
import Cod.Usuario;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Dell
 */
public class Menu_Principal extends javax.swing.JFrame {

    private ManejoUsuario user;
    private Usuario[] resultados;
    private Usuario oponente;

    public Menu_Principal(ManejoUsuario user) {
        this.user = user;
       
        initComponents();

        this.setLocationRelativeTo(null);

        panelList.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        bnjugar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        bncuenta = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        bnreportes = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        bncerrar = new javax.swing.JButton();
        panelList = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userList = new javax.swing.JList<>();
        bnseleccionar = new javax.swing.JButton();
        bncancel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("KATANA", 0, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("XIANGQI");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 170, 40));

        bnjugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imags/button2.png"))); // NOI18N
        bnjugar.setBorderPainted(false);
        bnjugar.setContentAreaFilled(false);
        bnjugar.setRolloverEnabled(false);
        bnjugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnjugarActionPerformed(evt);
            }
        });
        getContentPane().add(bnjugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 210, 80));

        jLabel9.setFont(new java.awt.Font("KATANA", 0, 22)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("CUENTA");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 170, 40));

        bncuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imags/button2.png"))); // NOI18N
        bncuenta.setBorderPainted(false);
        bncuenta.setContentAreaFilled(false);
        bncuenta.setRolloverEnabled(false);
        bncuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bncuentaActionPerformed(evt);
            }
        });
        getContentPane().add(bncuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 210, 80));

        jLabel8.setFont(new java.awt.Font("KATANA", 0, 22)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("XIANGQI");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 170, 40));

        jLabel10.setFont(new java.awt.Font("KATANA", 0, 22)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("REPORTES");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, 170, 40));

        bnreportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imags/button2.png"))); // NOI18N
        bnreportes.setBorderPainted(false);
        bnreportes.setContentAreaFilled(false);
        bnreportes.setRolloverEnabled(false);
        bnreportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnreportesActionPerformed(evt);
            }
        });
        getContentPane().add(bnreportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 210, 80));

        jLabel11.setFont(new java.awt.Font("KATANA", 0, 22)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("CERRAR SESION");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 530, 170, 40));

        bncerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imags/button2.png"))); // NOI18N
        bncerrar.setBorderPainted(false);
        bncerrar.setContentAreaFilled(false);
        bncerrar.setRolloverEnabled(false);
        bncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bncerrarActionPerformed(evt);
            }
        });
        getContentPane().add(bncerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 510, 210, 80));

        jScrollPane1.setViewportView(userList);

        bnseleccionar.setText("Seleccionar");
        bnseleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnseleccionarActionPerformed(evt);
            }
        });

        bncancel.setText("Cancelar");
        bncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bncancelActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        jLabel2.setText("Selecciona tu oponente");

        javax.swing.GroupLayout panelListLayout = new javax.swing.GroupLayout(panelList);
        panelList.setLayout(panelListLayout);
        panelListLayout.setHorizontalGroup(
            panelListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(panelListLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(bnseleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bncancel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
            .addGroup(panelListLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        panelListLayout.setVerticalGroup(
            panelListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bnseleccionar)
                    .addComponent(bncancel))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(panelList, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 320, 370));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imags/fondo1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bnjugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnjugarActionPerformed
        panelList.setVisible(true);

        DefaultListModel<String> modelo = new DefaultListModel<>();

        Usuario[] todosUsuarios = user.obtenerUsuarios();
        boolean hayOtrosJugadores = false;

        resultados = new Usuario[todosUsuarios.length];

        int index = 0;

        for (Usuario usuario : todosUsuarios) {
            if (usuario != null) {
                if (usuario.equals(user.obtenerUsuarioActual())) {
                    modelo.addElement("  [TU] " + usuario.getUsername() + " | Puntos: " + usuario.getPuntos());
                    bnseleccionar.setEnabled(false);
                } else {
                    modelo.addElement("  [PLAYER] " + usuario.getUsername() + " | Puntos: " + usuario.getPuntos());
                    hayOtrosJugadores = true;
                }
                resultados[index++] = usuario;
            }
        }

        userList.setModel(modelo);

        if (!hayOtrosJugadores) {
            JOptionPane.showMessageDialog(this, "No hay otros oponentes disponibles.", "Información", JOptionPane.INFORMATION_MESSAGE);
        }

        userList.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    String seleccionado = userList.getSelectedValue();

                    if (seleccionado != null && seleccionado.contains("[TU]")) {
                        bnseleccionar.setEnabled(false);
                    } else {
                        bnseleccionar.setEnabled(true);
                    }
                }
            }
        });

        userList.setModel(modelo);


    }//GEN-LAST:event_bnjugarActionPerformed

    private void bncuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bncuentaActionPerformed
         this.setVisible(false);
        new Cuenta(user).setVisible(true);
      
    }//GEN-LAST:event_bncuentaActionPerformed

    private void bnreportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnreportesActionPerformed
        this.setVisible(false);
        new Reportes(user).setVisible(true);
    }//GEN-LAST:event_bnreportesActionPerformed

    private void bncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bncerrarActionPerformed
        this.dispose();
        new Menu_Inicio(user).setVisible(true);
    }//GEN-LAST:event_bncerrarActionPerformed

    private void bnseleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnseleccionarActionPerformed

        int seleccionado = userList.getSelectedIndex();

        if (seleccionado >= 0) {
            oponente = resultados[seleccionado];
            
            Tablero tablero = new Tablero(user, oponente);
            this.setVisible(false);
            tablero.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Por favor selecciona un jugador.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_bnseleccionarActionPerformed

    private void bncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bncancelActionPerformed
        panelList.setVisible(false);
    }//GEN-LAST:event_bncancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            ManejoUsuario user;

            public void run() {
                new Menu_Principal(user).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bncancel;
    private javax.swing.JButton bncerrar;
    private javax.swing.JButton bncuenta;
    private javax.swing.JButton bnjugar;
    private javax.swing.JButton bnreportes;
    private javax.swing.JButton bnseleccionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelList;
    private javax.swing.JList<String> userList;
    // End of variables declaration//GEN-END:variables
}
