/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Inter;

import Cod.ManejoUsuario;

/**
 *
 * @author Dell
 */
public class Menu_Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Inicio
     */
    
    private ManejoUsuario user ;
    
    public Menu_Inicio(ManejoUsuario user) {
        this.user=user;
        initComponents();
        
        this.setLocationRelativeTo(null);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        bniniciar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        bnregistrar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        bnsalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("KATANA", 0, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Iniciar");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 170, 40));

        bniniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imags/button2.png"))); // NOI18N
        bniniciar.setBorderPainted(false);
        bniniciar.setContentAreaFilled(false);
        bniniciar.setRolloverEnabled(false);
        bniniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bniniciarActionPerformed(evt);
            }
        });
        getContentPane().add(bniniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 210, 80));

        jLabel6.setFont(new java.awt.Font("KATANA", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("REGISTRAR");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 170, 40));

        bnregistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imags/button2.png"))); // NOI18N
        bnregistrar.setBorderPainted(false);
        bnregistrar.setContentAreaFilled(false);
        bnregistrar.setFocusable(false);
        bnregistrar.setRolloverEnabled(false);
        bnregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnregistrarActionPerformed(evt);
            }
        });
        getContentPane().add(bnregistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 210, 80));

        jLabel7.setFont(new java.awt.Font("KATANA", 0, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("SALIR");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, 170, 40));

        bnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imags/button2.png"))); // NOI18N
        bnsalir.setBorderPainted(false);
        bnsalir.setContentAreaFilled(false);
        bnsalir.setRolloverEnabled(false);
        bnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnsalirActionPerformed(evt);
            }
        });
        getContentPane().add(bnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 210, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imags/ini2.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -2, 980, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bnregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnregistrarActionPerformed
       this.setVisible(false);
       new Registro(user).setVisible(true);
    }//GEN-LAST:event_bnregistrarActionPerformed

    private void bniniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bniniciarActionPerformed
        this.setVisible(false);
       new Iniciar_Sesion(user).setVisible(true);
    }//GEN-LAST:event_bniniciarActionPerformed

    private void bnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnsalirActionPerformed
      System.exit(0);
    }//GEN-LAST:event_bnsalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            ManejoUsuario user;
            public void run() {
                new Menu_Inicio(user).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bniniciar;
    private javax.swing.JButton bnregistrar;
    private javax.swing.JButton bnsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
