/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Inter;

import Cod.ManejoUsuario;
import Cod.Usuario;

/**
 *
 * @author Dell
 */
public class Ranking extends javax.swing.JPanel {
    private ManejoUsuario user;
    
    public Ranking(ManejoUsuario user) {
        this.user=user;
        initComponents();
        
        area.setLineWrap(true); 
        area.setWrapStyleWord(true);
         area.setEditable(false);
          
         
         mostrarRanking();
         
    }
    
    public void mostrarRanking() {
        
        area.setText("");
        
        Usuario[] rankingUsuarios = user.obtenerRanking();
        StringBuilder rankingTexto = new StringBuilder();

        for (int i = 0; i < rankingUsuarios.length; i++) {
            rankingTexto.append("[ ").append(i + 1).append(" ] ")
                        .append("Usuario: ").append(rankingUsuarios[i].getUsername()).append(" -- ")
                        .append("Puntos: ").append(rankingUsuarios[i].getPuntos()).append("\n\n");
        }

        area.setText(rankingTexto.toString());
        
        
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();

        setPreferredSize(new java.awt.Dimension(750, 580));

        area.setColumns(20);
        area.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        area.setForeground(new java.awt.Color(0, 0, 0));
        area.setRows(5);
        jScrollPane1.setViewportView(area);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
