/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Inter;

import Cod.ManejoUsuario;
import java.time.LocalDate;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class Registro extends javax.swing.JFrame {
    private ManejoUsuario user;
    /**
     * Creates new form Registro
     */
    public Registro(ManejoUsuario user) {
        this.user=user;
        initComponents();
        
        this.setLocationRelativeTo(null);
    }
    
    LocalDate today = LocalDate.now();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txpassword = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        bnIniciar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbfecha = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        bnX = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txpassword.setBackground(new java.awt.Color(102, 0, 0));
        txpassword.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        txpassword.setForeground(new java.awt.Color(255, 255, 255));
        txpassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txpassword.setBorder(null);
        txpassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txpasswordFocusLost(evt);
            }
        });
        txpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txpasswordActionPerformed(evt);
            }
        });
        getContentPane().add(txpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, 250, 40));

        jLabel3.setFont(new java.awt.Font("KATANA", 0, 38)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Crear Player");
        jLabel3.setToolTipText("");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 290, 100));

        jLabel13.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Siguiente");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 600, 140, 30));

        bnIniciar.setBackground(new java.awt.Color(255, 102, 102));
        bnIniciar.setFont(new java.awt.Font("Berlin Sans FB", 0, 22)); // NOI18N
        bnIniciar.setForeground(new java.awt.Color(255, 255, 255));
        bnIniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imags/button2.png"))); // NOI18N
        bnIniciar.setText(" ");
        bnIniciar.setBorderPainted(false);
        bnIniciar.setContentAreaFilled(false);
        bnIniciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnIniciarActionPerformed(evt);
            }
        });
        getContentPane().add(bnIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 580, 250, 70));

        jLabel4.setFont(new java.awt.Font("KATANA", 0, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Nombre usuario");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, 250, 30));

        txtusername.setBackground(new java.awt.Color(102, 0, 0));
        txtusername.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        txtusername.setForeground(new java.awt.Color(255, 255, 255));
        txtusername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtusername.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtusername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtusernameFocusLost(evt);
            }
        });
        txtusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusernameActionPerformed(evt);
            }
        });
        getContentPane().add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 250, 40));

        jLabel5.setFont(new java.awt.Font("KATANA", 0, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("ContraseNa");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 340, 250, 30));

        jLabel6.setFont(new java.awt.Font("KATANA", 0, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Fecha");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 440, 250, 30));

        lbfecha.setBackground(new java.awt.Color(102, 0, 0));
        lbfecha.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        lbfecha.setForeground(new java.awt.Color(255, 255, 255));
        lbfecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbfecha.setOpaque(true);
        lbfecha.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                lbfechaComponentAdded(evt);
            }
        });
        getContentPane().add(lbfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 470, 250, 40));

        jLabel1.setFont(new java.awt.Font("Japanese", 1, 62)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(" A E I");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 0, 310, 110));

        jLabel10.setFont(new java.awt.Font("Japanese", 1, 26)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("hoLA JA JA YQ AK A OE PXN A");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 690, 840, 70));

        jLabel11.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Back");
        jLabel11.setToolTipText("");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 50, 20));

        bnX.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        bnX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imags/button_back.png"))); // NOI18N
        bnX.setBorderPainted(false);
        bnX.setContentAreaFilled(false);
        bnX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnXActionPerformed(evt);
            }
        });
        getContentPane().add(bnX, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 70));

        jLabel12.setFont(new java.awt.Font("KATANA", 1, 40)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 102, 102));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imags/botonG.png"))); // NOI18N
        jLabel12.setToolTipText("");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 430, 150));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("KATANA", 0, 12)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imags/14.png"))); // NOI18N
        jLabel8.setOpaque(true);
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txpasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txpasswordFocusLost
        
    }//GEN-LAST:event_txpasswordFocusLost

    private void txpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txpasswordActionPerformed

    private void bnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnIniciarActionPerformed
        String username = txtusername.getText().trim();
        String password = txpassword.getText().trim();
        String fecha = lbfecha.getText().trim();

       

       
        if (!username.isEmpty()
            && !password.isEmpty()) {

            if (!user.usuarioExiste(username)) {
                
                if(password.length()!=5){
                    JOptionPane.showMessageDialog(null, "La contraseña debe tener exactamente 5 caracteres");
                    txpassword.setText("");
                }else{
                   
                    if (user.agregarUser(username, password, fecha, true)) {
                        JOptionPane.showMessageDialog(null, "Registrado Exitosamente");
                        this.setVisible(false);
                        new Menu_Principal(user).setVisible(true);

                    } else {
                        JOptionPane.showMessageDialog(null, "Algo salio mal, intenta de nuevo");
                    }
                }
                
                
            } else {
                JOptionPane.showMessageDialog(null, "Usuario existente");
            }

        } else {
            if ( username.isEmpty() || password.isEmpty() ) {
                JOptionPane.showMessageDialog(null, "¡Error! Asegúrese de llenar todos los campos");

            }
        }
    }//GEN-LAST:event_bnIniciarActionPerformed

    private void txtusernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtusernameFocusLost
        if (!txtusername.getText().isEmpty()) {
            lbfecha.setText("" + today);
        }
    }//GEN-LAST:event_txtusernameFocusLost

    private void txtusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernameActionPerformed

    private void lbfechaComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_lbfechaComponentAdded

    }//GEN-LAST:event_lbfechaComponentAdded

    private void bnXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnXActionPerformed
        this.setVisible(false);
        new Menu_Inicio(user).setVisible(true);
    }//GEN-LAST:event_bnXActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            ManejoUsuario user;
            public void run() {
                new Registro(user).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnIniciar;
    private javax.swing.JButton bnX;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lbfecha;
    private javax.swing.JTextField txpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
